### ISSUE TITLE
[FEATURE] Please update for 1.20.6 

### ISSUE THREAD

**Issue by Smol-Bean0** [DarkKronicle/AdvancedChatLog#9]
At present, you have version 1.20.6 available for Chatcore, Chathue, Chatbox. Would it be possible to also make it available for version 1.20.6 for Advanced Chat Log?

**Comment by Alfie51m** [comment]
Dark isn't currently maintaining his minecraft mods, the 1.20.6 updates was done by the community

**Comment by Smol-Bean0** [comment]
Oops I asked the wrong github page of it, i was meaning to ask one of those maintaining it
